apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1 
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service
        imagePullPolicy: IfNotPresent
        env:
        - name: PROJECT_ENV
          value: development
        - name: DB_NAME
          value: testDB
        - name: DB_USER
          value: testUser
        - name: DB_PASS
          value: testPassword
        - name: DB_HOST
          value: user-postgresdb
        - name: DB_PORT
          value: "5432"
        - name: PORT
          value: "8101"
        - name: JWT_SECRET
          value: secret
        - name: BACKEND_URL
          value: localhost
        ports:
        - containerPort: 8101
